### ISSUE TITLE
Support for enum types in schemas

### ISSUE THREAD

**Issue by bhimsenp** [medly/apifi#36]
The enum types in schemas are defined as follows:

```
    EnumName:
      type: string
      enum:
        - VALUE1
        - VALUE2
        - VALUE3
```
Right now there is no support to create model for such enums. Codegen creates Models with class as "kotlin.String" which is incorrect and fails during file generation.
